-- 1. Create the enumerated type for account types
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

-- 2. Structure of the `classification` table
CREATE TABLE public.classification (
    classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    classification_name character varying NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3. Structure of the `inventory` table
CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- 4. Relationship between classification and inventory (Foreign Key)
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id);

-- 5. Structure of the `account` table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 6. Insert data into the `classification` table
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- 7. Insert data into the `inventory` table
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, 
    inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
  )
VALUES   
    ('Chevy', 'Camaro', '2018', 'If you want to look cool this is the ar you need!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
    ('Batmobile', 'Custom', '2007', 'Ever want to be a super hero?', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 29887, 'Black', 1),
    ('FBI', 'Surveillance Van', '2016', 'Do you like police shows?', '/images/survan.jpg', '/images/survan-tn.jpg', 20000, 19851, 'Brown', 1),
    ('Dog ', 'Car', '1997', 'Do you like dogs?', '/images/dog-car.jpg', '/images/dog-car-tn.jpg', 35000, 71632, 'White', 1),
    ('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact.', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 28045, 41205, 'Yellow', 3),
    ('Lamborghini', 'Adventador', '2016', 'This V-12 engine packs a punch.', '/images/adventador.jpg', '/images/adventador-tn.jpg', 417650, 71003, 'Blue', 2),
    ('Aerocar International', 'Aerocar', '1963', 'Are you sick of rushhour trafic?', '/images/aerocar.jpg', '/images/aerocar-tn.jpg', 700000, 18956, 'Red', 1),
    ('Monster', 'Truck', '1995', 'Most trucks are for working, this one is for fun.', '/images/monster-truck.jpg', '/images/monster-truck-tn.jpg', 150000, 3998, 'purple', 1),
    ('Cadillac', 'Escalade', '2019', 'This stylin car is great for any occasion.', '/images/escalade.jpg', '/images/escalade-tn.jpg', 75195, 41958, 'Black', 4),
    ('GM', 'Hummer', '2016', 'Do you have 6 kids and like to go offroading? This Hummer has small interiors.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 4),
    ('Mechanic', 'Special', '1964', 'Not sure where this car came from.', '/images/mechanic.jpg', '/images/mechanic-tn.jpg', 100, 200125, 'Rust', 5),
    ('Ford', 'Model T', '1921', 'The Ford Model T can be a bit tricky to drive.', '/images/model-t.jpg', '/images/model-t-tn.jpg', 30000, 26357, 'Black', 5),
    ('Mystery', 'Machine', '1999', 'Scooby and the gang always found luck.', '/images/mystery-van.jpg', '/images/mystery-van-tn.jpg', 10000, 128564, 'Green', 1),
    ('Spartan', 'Fire Truck', '2012', 'Emergencies happen often.', '/images/fire-truck.jpg', '/images/fire-truck-tn.jpg', 50000, 38522, 'Red', 4),
    ('Ford', 'Crown Victoria', '2013', 'After the police force updated their fleet.', '/images/crwn-vic.jpg', '/images/crwn-vic-tn.jpg', 10000, 108247, 'White', 5);

-- 8. Final updates from Task 1 (Reemplazo de descripción y rutas de imágenes)
-- Esto asegura que los cambios requeridos se apliquen automáticamente al reconstruir.

UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');